### PR TITLE
feat: grids

### PR DESCRIPTION
**Pull request by harshitadaswani**
- added 2x2 responsive grids
- added 3x3 responsive grids

### CODE REVIEW

**Review by JantuDeb — APPROVED** [review]
Suggested a class name for grid

**Review by shaksham08 — APPROVED** [review]
Looks good to me

**Comment by bhargaviRdy** [comment]
When seen in mobile view, the 3 * 3 responsive grids are overflowing the grid-container
image
Have a look if you missed it

**Comment by harshitadaswani** [comment]
> When seen in mobile view, the 3 * 3 responsive grids are overflowing the grid-container image Have a look if you missed it

Yeah, I had missed it. Thank you, for pointing it out. I will resolve it.

**Pull request merged**
